using System.Text.Json;
using RtkSharp.Filters.Commands.Gh;

namespace RtkSharp.Filters.Tests.Commands.Gh;

/// <summary>
/// Tests for <see cref="GhFilters"/>. The JSON-formatting and markdown-filtering helpers are pure
/// functions ported from <c>src/cmds/git/gh_cmd.rs</c>, so most of this suite exercises them directly
/// with the same inline JSON shapes the Rust module's own tests use. Moved from
/// <c>RtkSharp.Tests.Commands.GhCommandTests</c> when the underlying pure methods moved from
/// <c>RtkSharp.Commands.Gh.GhCommand</c> to <see cref="GhFilters"/> (Task 5 of the filters-library
/// extraction). Argument-parsing helpers (<c>HasJsonFlag</c>, <c>ExtractIdentifierAndExtraArgs</c>,
/// <c>ParseOptionalIdentifier</c>, the <c>ShouldPassthrough*</c> guards, <c>HasNonDiffFormatFlag</c>,
/// <c>PrStatusJsonFields</c>) and dispatch tests were not moved — they remain in the original
/// <c>GhCommandTests</c> alongside <c>GhCommand</c>. The format expectations are oracle-derived: <c>gh
/// pr view</c>/<c>pr list</c>/<c>issue list</c> were confirmed byte-identical against the reference
/// <c>rtk.exe</c> for the equivalent live invocations against this repository's GitHub remote.
/// </summary>
public sealed class GhFiltersTests
{
    // ==================== Truncate (utils::truncate) ====================

    [Fact]
    public void Truncate_ShortUnchanged() => Assert.Equal("short", GhFilters.Truncate("short", 10));

    [Fact]
    public void Truncate_LongGetsEllipsis() =>
        Assert.Equal("this is a ve...", GhFilters.Truncate("this is a very long string", 15));

    [Fact]
    public void Truncate_MaxLenBelowThree() => Assert.Equal("...", GhFilters.Truncate("abcdef", 2));

    [Fact]
    public void Truncate_MultibyteCountsRunes()
    {
        Assert.Equal("🚀🎉🔥abc", GhFilters.Truncate("🚀🎉🔥abc", 6)); // exact fit
        Assert.Equal("🚀🎉🔥ab...", GhFilters.Truncate("🚀🎉🔥abcdef", 8)); // truncated on rune boundary
    }

    // ==================== state_icon ====================

    [Theory]
    [InlineData("OPEN", "[open]")]
    [InlineData("MERGED", "[merged]")]
    [InlineData("CLOSED", "[closed]")]
    [InlineData("WEIRD", "[unknown]")]
    public void StateIcon_NonUltra(string state, string expected) => Assert.Equal(expected, GhFilters.StateIcon(state, false));

    [Theory]
    [InlineData("OPEN", "O")]
    [InlineData("MERGED", "M")]
    [InlineData("CLOSED", "C")]
    [InlineData("WEIRD", "?")]
    public void StateIcon_Ultra(string state, string expected) => Assert.Equal(expected, GhFilters.StateIcon(state, true));

    // ==================== format_pr_list ====================

    [Fact]
    public void FormatPrList_Basic()
    {
        const string json = """
        [{"number":10,"title":"Fix bug","state":"OPEN","author":{"login":"octo"}},
         {"number":9,"title":"Add feature","state":"MERGED","author":{"login":"cat"}}]
        """;
        using var doc = JsonDocument.Parse(json);
        var result = GhFilters.FormatPrList(doc.RootElement, false);
        Assert.Equal(
            "Pull Requests\n  [open] #10 Fix bug (octo)\n  [merged] #9 Add feature (cat)\n",
            result);
    }

    [Fact]
    public void FormatPrList_EmptyArray()
    {
        using var doc = JsonDocument.Parse("[]");
        Assert.Equal("No Pull Requests\n", GhFilters.FormatPrList(doc.RootElement, false));
        Assert.Equal("No PRs\n", GhFilters.FormatPrList(doc.RootElement, true));
    }

    [Fact]
    public void FormatPrList_UltraHeaderAndIcons()
    {
        const string json = """[{"number":1,"title":"x","state":"OPEN","author":{"login":"a"}}]""";
        using var doc = JsonDocument.Parse(json);
        Assert.Equal("PRs\n  O #1 x (a)\n", GhFilters.FormatPrList(doc.RootElement, true));
    }

    [Fact]
    public void FormatPrList_NonArrayReturnsEmpty()
    {
        using var doc = JsonDocument.Parse("""{"number":1}""");
        Assert.Equal(string.Empty, GhFilters.FormatPrList(doc.RootElement, false));
    }

    // ==================== format_pr_view ====================

    [Fact]
    public void FormatPrView_BadgesOnlyBodyShowsFallbackNote()
    {
        const string json = """
        {"number":42,"title":"Test PR","state":"OPEN","author":{"login":"octocat"},
         "url":"https://github.com/foo/bar/pull/42","mergeable":"MERGEABLE",
         "body":"<!-- Auto-generated by bot -->\n[![CI](https://shields.io/badge.svg)](https://ci.example.com)\n![screenshot](https://example.com/img.png)\n---\n"}
        """;
        using var doc = JsonDocument.Parse(json);
        var result = GhFilters.FormatPrView(doc.RootElement, false);
        Assert.Contains("(body contained only badges/images/comments)", result);
    }

    [Fact]
    public void FormatPrView_ContentBodyNoFallbackNote()
    {
        const string json = """
        {"number":42,"title":"Test PR","state":"OPEN","author":{"login":"octocat"},
         "url":"https://github.com/foo/bar/pull/42","mergeable":"MERGEABLE",
         "body":"## Summary\nFix the thing.\n"}
        """;
        using var doc = JsonDocument.Parse(json);
        var result = GhFilters.FormatPrView(doc.RootElement, false);
        Assert.DoesNotContain("(body contained only badges/images/comments)", result);
        Assert.Contains("## Summary", result);
        Assert.Contains("Fix the thing.", result);
    }

    [Fact]
    public void FormatPrView_EmptyBodyNoFallbackNote()
    {
        const string json = """
        {"number":42,"title":"Test PR","state":"OPEN","author":{"login":"octocat"},
         "url":"https://github.com/foo/bar/pull/42","mergeable":"MERGEABLE","body":""}
        """;
        using var doc = JsonDocument.Parse(json);
        Assert.DoesNotContain("(body contained only badges/images/comments)", GhFilters.FormatPrView(doc.RootElement, false));
    }

    [Fact]
    public void FormatPrView_HeaderAuthorMergeableAndChecks()
    {
        // statusCheckRollup counts SUCCESS via conclusion OR state; failure via conclusion OR state.
        const string json = """
        {"number":7,"title":"Big change","state":"OPEN","author":{"login":"dev"},
         "url":"https://x/7","mergeable":"CONFLICTING",
         "statusCheckRollup":[{"conclusion":"SUCCESS"},{"state":"SUCCESS"},{"conclusion":"FAILURE"}]}
        """;
        using var doc = JsonDocument.Parse(json);
        var result = GhFilters.FormatPrView(doc.RootElement, false);
        Assert.StartsWith("[open] PR #7: Big change\n  dev\n  OPEN | [x]\n", result);
        Assert.Contains("  Checks: 2/3 passed\n", result);
        Assert.Contains("  [warn] 1 checks failed\n", result);
    }

    [Fact]
    public void FormatPrView_UltraChecksCompact()
    {
        const string json = """
        {"number":7,"title":"t","state":"OPEN","author":{"login":"d"},"url":"u","mergeable":"MERGEABLE",
         "statusCheckRollup":[{"conclusion":"SUCCESS"},{"conclusion":"FAILURE"}]}
        """;
        using var doc = JsonDocument.Parse(json);
        var result = GhFilters.FormatPrView(doc.RootElement, true);
        Assert.Contains("  [x]1/2  1 fail\n", result);
    }

    [Fact]
    public void FormatPrView_ReviewsAsArraySkipsReviewsLine()
    {
        // Real gh --json reviews returns a plain array (not {nodes:[...]}), so the reviews line is skipped.
        const string json = """
        {"number":1,"title":"t","state":"MERGED","author":{"login":"a"},"url":"u","mergeable":"UNKNOWN",
         "reviews":[{"state":"APPROVED"}]}
        """;
        using var doc = JsonDocument.Parse(json);
        Assert.DoesNotContain("Reviews:", GhFilters.FormatPrView(doc.RootElement, false));
    }

    [Fact]
    public void FormatPrView_ReviewsNodesShapeRendersReviewsLine()
    {
        // GraphQL-shaped reviews.nodes IS honored when present.
        const string json = """
        {"number":1,"title":"t","state":"OPEN","author":{"login":"a"},"url":"u","mergeable":"MERGEABLE",
         "reviews":{"nodes":[{"state":"APPROVED"},{"state":"CHANGES_REQUESTED"},{"state":"APPROVED"}]}}
        """;
        using var doc = JsonDocument.Parse(json);
        Assert.Contains("  Reviews: 2 approved, 1 changes requested\n", GhFilters.FormatPrView(doc.RootElement, false));
    }

    // ==================== format_issue_list ====================

    [Fact]
    public void FormatIssueList_Basic()
    {
        const string json = """
        [{"number":5,"title":"Broken","state":"OPEN","author":{"login":"x"}},
         {"number":4,"title":"Done","state":"CLOSED","author":{"login":"y"}}]
        """;
        using var doc = JsonDocument.Parse(json);
        Assert.Equal(
            "Issues\n  [open] #5 Broken\n  [closed] #4 Done\n",
            GhFilters.FormatIssueList(doc.RootElement, false));
    }

    [Fact]
    public void FormatIssueList_EmptyArray()
    {
        using var doc = JsonDocument.Parse("[]");
        Assert.Equal("No Issues\n", GhFilters.FormatIssueList(doc.RootElement, false));
    }

    [Fact]
    public void FormatIssueList_UltraIcons()
    {
        const string json = """
        [{"number":5,"title":"a","state":"OPEN"},{"number":4,"title":"b","state":"CLOSED"}]
        """;
        using var doc = JsonDocument.Parse(json);
        Assert.Equal("Issues\n  O #5 a\n  C #4 b\n", GhFilters.FormatIssueList(doc.RootElement, true));
    }

    // ==================== format_issue_view ====================

    [Fact]
    public void FormatIssueView_Basic()
    {
        const string json = """
        {"number":99,"title":"Crash","state":"OPEN","author":{"login":"octocat"},
         "url":"https://github.com/foo/bar/issues/99","body":"## Repro\nDo the thing.\n"}
        """;
        using var doc = JsonDocument.Parse(json);
        var result = GhFilters.FormatIssueView(doc.RootElement);
        Assert.StartsWith("[open] Issue #99: Crash\n  Author: @octocat\n  Status: OPEN\n  URL: https://github.com/foo/bar/issues/99\n", result);
        Assert.Contains("\n  Description:\n    ## Repro\n    Do the thing.\n", result);
    }

    [Fact]
    public void FormatIssueView_BadgesOnlyBodyShowsFallbackNote()
    {
        const string json = """
        {"number":99,"title":"t","state":"OPEN","author":{"login":"octocat"},"url":"u",
         "body":"<!-- Auto-generated -->\n[![status](https://shields.io/s.svg)](https://example.com)\n"}
        """;
        using var doc = JsonDocument.Parse(json);
        Assert.Contains("Description: (body contained only badges/images/comments)", GhFilters.FormatIssueView(doc.RootElement));
    }

    // ==================== format_pr_status ====================

    [Fact]
    public void FormatPrStatus_IncludesCurrentBranchSummary()
    {
        const string json = """
        {"currentBranch":{"number":934,"title":"fix wrappers for standardization and exit codes",
          "reviewDecision":"CHANGES_REQUESTED",
          "statusCheckRollup":[{"conclusion":"SUCCESS"},{"state":"SUCCESS"},{"conclusion":"FAILURE"}]},
         "createdBy":[]}
        """;
        using var doc = JsonDocument.Parse(json);
        var result = GhFilters.FormatPrStatus(doc.RootElement);
        Assert.Contains("Current Branch", result);
        Assert.Contains("#934", result);
        Assert.Contains("CHANGES_REQUESTED", result);
        Assert.Contains("checks 2/3", result);
        Assert.Contains("fail 1", result);
    }

    [Fact]
    public void FormatPrStatus_ListsCreatedByPrs()
    {
        const string json = """
        {"currentBranch":null,
         "createdBy":[{"number":1,"title":"one","reviewDecision":"APPROVED"},
                      {"number":2,"title":"two"}]}
        """;
        using var doc = JsonDocument.Parse(json);
        var result = GhFilters.FormatPrStatus(doc.RootElement);
        Assert.DoesNotContain("Current Branch", result);
        Assert.Contains("Your PRs (2):\n", result);
        Assert.Contains("  #1 one [APPROVED]\n", result);
        Assert.Contains("  #2 two [PENDING]\n", result);
    }

    // ==================== format_pr_checks ====================

    [Fact]
    public void FormatPrChecks_SummarizesCounts()
    {
        const string stdout = "build\tpass\t1s\nlint\tfail\t2s\ndeploy\tpending\nunit\tpass\t3s\n";
        var result = GhFilters.FormatPrChecks(stdout);
        Assert.Contains("CI Checks Summary:\n", result);
        Assert.Contains("  [ok] Passed: 2\n", result);
        Assert.Contains("  [FAIL] Failed: 1\n", result);
        Assert.Contains("  [pending] Pending: 1\n", result);
        Assert.Contains("  Failed checks:\n", result);
        Assert.Contains("lint", result);
    }

    // ==================== filter_markdown_body ====================

    [Fact]
    public void FilterMarkdownBody_HtmlCommentSingleLine()
    {
        var result = GhFilters.FilterMarkdownBody("Hello\n<!-- this is a comment -->\nWorld");
        Assert.DoesNotContain("<!--", result);
        Assert.Contains("Hello", result);
        Assert.Contains("World", result);
    }

    [Fact]
    public void FilterMarkdownBody_HtmlCommentMultiline()
    {
        var result = GhFilters.FilterMarkdownBody("Before\n<!--\nmultiline\ncomment\n-->\nAfter");
        Assert.DoesNotContain("<!--", result);
        Assert.DoesNotContain("multiline", result);
        Assert.Contains("Before", result);
        Assert.Contains("After", result);
    }

    [Fact]
    public void FilterMarkdownBody_BadgeLines()
    {
        var result = GhFilters.FilterMarkdownBody(
            "# Title\n[![CI](https://img.shields.io/badge.svg)](https://github.com/actions)\nSome text");
        Assert.DoesNotContain("shields.io", result);
        Assert.Contains("# Title", result);
        Assert.Contains("Some text", result);
    }

    [Fact]
    public void FilterMarkdownBody_ImageOnlyLines()
    {
        var result = GhFilters.FilterMarkdownBody("# Title\n![screenshot](https://example.com/img.png)\nSome text");
        Assert.DoesNotContain("![screenshot]", result);
        Assert.Contains("# Title", result);
        Assert.Contains("Some text", result);
    }

    [Fact]
    public void FilterMarkdownBody_HorizontalRules()
    {
        var result = GhFilters.FilterMarkdownBody("Section 1\n---\nSection 2\n***\nSection 3\n___\nEnd");
        Assert.DoesNotContain("---", result);
        Assert.DoesNotContain("***", result);
        Assert.DoesNotContain("___", result);
        Assert.Contains("Section 1", result);
        Assert.Contains("Section 2", result);
        Assert.Contains("Section 3", result);
    }

    [Fact]
    public void FilterMarkdownBody_BlankLinesCollapse()
    {
        var result = GhFilters.FilterMarkdownBody("Line 1\n\n\n\n\nLine 2");
        Assert.DoesNotContain("\n\n\n", result);
        Assert.Contains("Line 1", result);
        Assert.Contains("Line 2", result);
    }

    [Fact]
    public void FilterMarkdownBody_CodeBlockPreserved()
    {
        var result = GhFilters.FilterMarkdownBody(
            "Text before\n```python\n<!-- not a comment -->\n![not an image](url)\n---\n```\nText after");
        Assert.Contains("<!-- not a comment -->", result);
        Assert.Contains("![not an image](url)", result);
        Assert.Contains("---", result);
        Assert.Contains("Text before", result);
        Assert.Contains("Text after", result);
    }

    [Fact]
    public void FilterMarkdownBody_Empty() => Assert.Equal(string.Empty, GhFilters.FilterMarkdownBody(""));

    [Fact]
    public void FilterMarkdownBody_MeaningfulContentPreserved()
    {
        var result = GhFilters.FilterMarkdownBody(
            "## Summary\n- Item 1\n- Item 2\n\n[Link](https://example.com)\n\n| Col1 | Col2 |\n| --- | --- |\n| a | b |");
        Assert.Contains("## Summary", result);
        Assert.Contains("- Item 1", result);
        Assert.Contains("- Item 2", result);
        Assert.Contains("[Link](https://example.com)", result);
        Assert.Contains("| Col1 | Col2 |", result);
    }

    [Fact]
    public void FilterMarkdownBody_TokenSavings()
    {
        const string input = """
        <!-- This PR template is auto-generated -->
        <!-- Please fill in the following sections -->

        ## Summary

        Added smart markdown filtering for gh issue/pr view commands.

        [![CI](https://img.shields.io/github/actions/workflow/status/rtk-ai/rtk/ci.yml)](https://github.com/rtk-ai/rtk/actions)
        [![Coverage](https://img.shields.io/codecov/c/github/rtk-ai/rtk)](https://codecov.io/gh/rtk-ai/rtk)

        ![screenshot](https://user-images.githubusercontent.com/123/screenshot.png)

        ---

        ## Changes

        - Filter HTML comments
        - Filter badge lines
        - Filter image-only lines
        - Collapse blank lines

        ***

        ## Test Plan

        - [x] Unit tests added
        - [x] Snapshot tests pass
        - [ ] Manual testing

        ___

        <!-- Do not edit below this line -->
        <!-- Auto-generated footer -->
        """;

        var result = GhFilters.FilterMarkdownBody(input);

        static int CountTokens(string text) =>
            text.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries).Length;

        var savings = 100.0 - (CountTokens(result) / (double)CountTokens(input) * 100.0);
        Assert.True(savings >= 30.0, $"Expected >=30% savings, got {savings:F1}%");

        Assert.Contains("## Summary", result);
        Assert.Contains("## Changes", result);
        Assert.Contains("## Test Plan", result);
        Assert.Contains("Filter HTML comments", result);
    }

    // ==================== format_run_list ====================

    [Fact]
    public void FormatRunList_Basic()
    {
        const string json = """
        [{"databaseId":111,"name":"CI","status":"completed","conclusion":"success"},
         {"databaseId":222,"name":"Deploy","status":"completed","conclusion":"failure"},
         {"databaseId":333,"name":"Lint","status":"in_progress","conclusion":null},
         {"databaseId":444,"name":"Nightly","status":"completed","conclusion":"cancelled"},
         {"databaseId":555,"name":"Queued","status":"queued","conclusion":null}]
        """;
        using var doc = JsonDocument.Parse(json);
        Assert.Equal(
            "Workflow Runs\n  [ok] CI [111]\n  [FAIL] Deploy [222]\n  [time] Lint [333]\n  [X] Nightly [444]\n  [pending] Queued [555]\n",
            GhFilters.FormatRunList(doc.RootElement, false));
    }

    [Fact]
    public void FormatRunList_UltraIcons()
    {
        const string json = """
        [{"databaseId":1,"name":"CI","status":"completed","conclusion":"success"},
         {"databaseId":2,"name":"D","status":"completed","conclusion":"failure"},
         {"databaseId":3,"name":"L","status":"in_progress","conclusion":null},
         {"databaseId":4,"name":"N","status":"completed","conclusion":"cancelled"},
         {"databaseId":5,"name":"Q","status":"queued","conclusion":null}]
        """;
        using var doc = JsonDocument.Parse(json);
        Assert.Equal(
            "Runs\n  [ok] CI [1]\n  [x] D [2]\n  ~ L [3]\n  X N [4]\n  ? Q [5]\n",
            GhFilters.FormatRunList(doc.RootElement, true));
    }

    [Fact]
    public void FormatRunList_EmptyArrayJustHeader()
    {
        using var doc = JsonDocument.Parse("[]");
        Assert.Equal("Workflow Runs\n", GhFilters.FormatRunList(doc.RootElement, false));
        Assert.Equal("Runs\n", GhFilters.FormatRunList(doc.RootElement, true));
    }

    [Fact]
    public void FormatRunList_NonArrayReturnsEmpty()
    {
        using var doc = JsonDocument.Parse("""{"databaseId":1}""");
        Assert.Equal(string.Empty, GhFilters.FormatRunList(doc.RootElement, false));
    }

    // ==================== format_run_view ====================

    [Fact]
    public void FormatRunView_WithId() =>
        Assert.StartsWith("Workflow Run #12345\n", GhFilters.FormatRunView(string.Empty, "12345"));

    [Fact]
    public void FormatRunView_WithoutIdNoEmptyHash()
    {
        var output = GhFilters.FormatRunView(string.Empty, string.Empty);
        Assert.StartsWith("Workflow Run\n", output);
        Assert.DoesNotContain("#\n", output);
    }

    [Fact]
    public void FormatRunView_KeepsStatusAndConclusionSkipsJobsSuccess()
    {
        const string stdout =
            "X CI · 12345\nTriggered via push\n\nStatus: completed\nConclusion: failure\n\nJOBS\n✓ build in 1m\n✓ lint (success)\nX deploy failed\n";
        var result = GhFilters.FormatRunView(stdout, "12345");
        Assert.Equal(
            "Workflow Run #12345\n  Status: completed\n  Conclusion: failure\n  [FAIL] X deploy failed\n",
            result);
    }

    // ==================== format_repo_view ====================

    [Fact]
    public void FormatRepoView_PublicWithDescription()
    {
        const string json = """
        {"name":"rtk","owner":{"login":"rtk-ai"},"description":"CLI proxy",
         "url":"https://github.com/rtk-ai/rtk","stargazerCount":68000,"forkCount":4200,"isPrivate":false}
        """;
        using var doc = JsonDocument.Parse(json);
        Assert.Equal(
            "rtk-ai/rtk\n  [public]\n  CLI proxy\n  68000 stars | 4200 forks\n  https://github.com/rtk-ai/rtk\n",
            GhFilters.FormatRepoView(doc.RootElement));
    }

    [Fact]
    public void FormatRepoView_PrivateNoDescriptionOmitsLine()
    {
        const string json = """
        {"name":"secret","owner":{"login":"me"},"description":"","url":"u",
         "stargazerCount":0,"forkCount":0,"isPrivate":true}
        """;
        using var doc = JsonDocument.Parse(json);
        Assert.Equal(
            "me/secret\n  [private]\n  0 stars | 0 forks\n  u\n",
            GhFilters.FormatRepoView(doc.RootElement));
    }
}
