<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>RtkSharp.Filters</PackageId>
    <AssemblyName>RtkSharp.Filters</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RtkSharp.Filters.Tests" />
  </ItemGroup>

</Project>
