using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;

namespace RtkSharp.Learn;

/// <summary>
/// Formats and persists <c>rtk learn</c>'s correction rules: a console text report and a
/// <c>.claude/rules/cli-corrections.md</c> markdown file. Faithful port of Rust
/// <c>src/learn/report.rs</c> (186 lines including its inline test module).
/// </summary>
public static class LearnReport
{
    /// <summary>
    /// Renders the console text report: a one-line summary header followed by one entry per rule
    /// (with an occurrence-count marker when seen more than once, and the error's first line as a
    /// hint). Faithful port of Rust <c>format_console_report</c> (<c>learn/report.rs</c>:9-52).
    /// </summary>
    /// <param name="rules">The deduplicated correction rules to report.</param>
    /// <param name="totalCorrections">The total (pre-deduplication, post-confidence-filter) correction count.</param>
    /// <param name="sessions">The number of sessions scanned.</param>
    /// <param name="days">The <c>--since</c> day window used for the scan.</param>
    /// <returns>The rendered report text.</returns>
    public static string FormatConsoleReport(IReadOnlyList<CorrectionRule> rules, int totalCorrections, int sessions, ulong days)
    {
        var output = new StringBuilder();

        output.Append(
            $"RTK Learn -- {rules.Count} rules from {totalCorrections} corrections ({sessions} sessions, {days} days)\n");

        if (rules.Count == 0)
        {
            output.Append("\nNo CLI corrections detected.\n");
            return output.ToString();
        }

        output.Append('\n');

        foreach (var rule in rules)
        {
            var countMarker = rule.Occurrences > 1 ? $"[{rule.Occurrences}x] " : "     ";

            output.Append($"{countMarker}{rule.WrongPattern}  →  {rule.RightPattern}\n");

            // Show error snippet (first line only).
            var errorLine = FirstLine(rule.ExampleError).Trim();
            if (errorLine.Length > 0)
            {
                output.Append($"     Error: {errorLine}\n");
            }
        }

        return output.ToString();
    }

    private static string FirstLine(string text)
    {
        var idx = text.IndexOf('\n');
        return idx < 0 ? text : text[..idx];
    }

    /// <summary>
    /// Writes the <c>.claude/rules/cli-corrections.md</c> file: rules grouped by base command
    /// (alphabetically sorted sections), each as a <c>Use `right` not `wrong`</c> bullet with an
    /// occurrence-count note when seen more than once. Faithful port of Rust <c>write_rules_file</c>
    /// (<c>learn/report.rs</c>:54-110).
    /// </summary>
    /// <param name="rules">The deduplicated correction rules to write.</param>
    /// <param name="path">The destination file path.</param>
    public static void WriteRulesFile(IReadOnlyList<CorrectionRule> rules, string path)
    {
        var parent = Path.GetDirectoryName(path);
        if (!string.IsNullOrEmpty(parent))
        {
            Directory.CreateDirectory(parent);
        }

        var content = new StringBuilder();
        content.Append("# CLI Corrections (auto-generated by rtk learn)\n");
        content.Append("# Run `rtk learn --write-rules` to update\n\n");

        if (rules.Count == 0)
        {
            content.Append("No CLI corrections detected yet.\n");
            File.WriteAllText(path, content.ToString());
            return;
        }

        // Group by base command.
        var grouped = new Dictionary<string, List<CorrectionRule>>(StringComparer.Ordinal);
        foreach (var rule in rules)
        {
            if (!grouped.TryGetValue(rule.BaseCommand, out var list))
            {
                list = [];
                grouped[rule.BaseCommand] = list;
            }

            list.Add(rule);
        }

        // Sort base commands alphabetically.
        var baseCommands = grouped.Keys.ToList();
        baseCommands.Sort(StringComparer.Ordinal);

        foreach (var baseCmd in baseCommands)
        {
            var rulesForCmd = grouped[baseCmd];

            // Capitalize first letter for section header.
            var sectionHeader = CapitalizeFirst(baseCmd);
            content.Append($"## {sectionHeader}\n");

            foreach (var rule in rulesForCmd)
            {
                var occurrenceNote = rule.Occurrences > 1 ? $" (seen {rule.Occurrences}x)" : string.Empty;

                content.Append($"- Use `{rule.RightPattern}` not `{rule.WrongPattern}`{occurrenceNote}\n");
            }

            content.Append('\n');
        }

        File.WriteAllText(path, content.ToString());
    }

    private static string CapitalizeFirst(string s)
    {
        if (s.Length == 0)
        {
            return string.Empty;
        }

        return char.ToUpper(s[0], CultureInfo.InvariantCulture) + s[1..];
    }
}
