using System.Text.RegularExpressions;

namespace RtkSharp.Rewrite;

/// <summary>
/// The full table of rewrite rules used to detect raw shell commands that have a
/// token-optimized <c>rtk</c> equivalent. Transcribed verbatim, in source order, from
/// the Rust <c>RULES</c> array in <c>src/discover/rules.rs</c>. Order matters: the
/// rewrite engine uses first-match-wins semantics.
/// </summary>
public static class RewriteRules
{
    /// <summary>
    /// All 75 rewrite rules, in the same order as <c>src/discover/rules.rs</c>.
    /// </summary>
    public static IReadOnlyList<RewriteRule> All { get; } = BuildRules();

    /// <summary>
    /// Constructs a single <see cref="RewriteRule"/>, compiling its pattern once.
    /// </summary>
    /// <param name="pattern">The regex source string, transcribed verbatim from rules.rs.</param>
    /// <param name="rtkCmd">The rtk-wrapped command to rewrite to.</param>
    /// <param name="rewritePrefixes">The raw command prefixes this rule recognizes.</param>
    /// <param name="category">The category this rule belongs to.</param>
    /// <param name="savingsPct">The expected token savings percentage.</param>
    /// <returns>The constructed rewrite rule with its pattern compiled.</returns>
    private static RewriteRule R(
        string pattern,
        string rtkCmd,
        string[] rewritePrefixes,
        string category,
        double savingsPct) =>
        new(pattern, new Regex(pattern, RegexOptions.Compiled), rtkCmd, rewritePrefixes, category, savingsPct);

    private static IReadOnlyList<RewriteRule> BuildRules() =>
    [
        R(
            @"^(?:git|yadm)\s+(?:-[Cc]\s+\S+\s+)*(status|log|diff|show|add|commit|push|pull|branch|fetch|stash|worktree)",
            "rtk git",
            ["git", "yadm"],
            "Git",
            70.0),
        R(
            @"^gh\s+(pr|issue|run|repo|api|release)",
            "rtk gh",
            ["gh"],
            "GitHub",
            82.0),
        R(
            @"^glab\s+(mr|issue|ci|pipeline|api|release)",
            "rtk glab",
            ["glab"],
            "GitLab",
            82.0),
        R(
            @"^cargo\s+(build|test|clippy|check|fmt|install)",
            "rtk cargo",
            ["cargo"],
            "Cargo",
            80.0),
        R(
            @"^pnpm\s+(exec|i|install|list|ls|outdated|run|run-script)",
            "rtk pnpm",
            ["pnpm"],
            "PackageManager",
            80.0),
        R(
            @"^npm\s+(exec|run|run-script|rum|urn|x)(\s|$)",
            "rtk npm",
            ["npm"],
            "PackageManager",
            70.0),
        R(
            @"^npx\s+",
            "rtk npx",
            ["npx"],
            "PackageManager",
            70.0),
        R(
            @"^(cat|head|tail)\s+",
            "rtk read",
            ["cat", "head", "tail"],
            "Files",
            60.0),
        R(
            @"^(rg|grep)\s+",
            "rtk grep",
            ["rg", "grep"],
            "Files",
            75.0),
        R(
            @"^ls(\s|$)",
            "rtk ls",
            ["ls"],
            "Files",
            65.0),
        R(
            @"^find\s+",
            "rtk find",
            ["find"],
            "Files",
            70.0),
        R(
            @"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?tsc(\s|$)",
            "rtk tsc",
            [
                "npm exec tsc",
                "npm rum tsc",
                "npm run tsc",
                "npm run-script tsc",
                "npm tsc",
                "npm urn tsc",
                "npm x tsc",
                "npx tsc",
                "pnpm dlx tsc",
                "pnpm exec tsc",
                "pnpm run tsc",
                "pnpm run-script tsc",
                "pnpm tsc",
                "pnpx tsc",
                "tsc",
            ],
            "Build",
            83.0),
        R(
            @"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?(biome|eslint|lint)(\s|$)",
            "rtk lint",
            [
                "biome",
                "eslint",
                "lint",
                "npm biome",
                "npm eslint",
                "npm exec biome",
                "npm exec eslint",
                "npm lint",
                "npm rum biome",
                "npm rum eslint",
                "npm rum lint",
                "npm run biome",
                "npm run eslint",
                "npm run lint",
                "npm run-script biome",
                "npm run-script eslint",
                "npm run-script lint",
                "npm urn biome",
                "npm urn eslint",
                "npm urn lint",
                "npm x biome",
                "npm x eslint",
                "npx biome",
                "npx eslint",
                "npx lint",
                "pnpm biome",
                "pnpm dlx biome",
                "pnpm dlx eslint",
                "pnpm eslint",
                "pnpm exec biome",
                "pnpm exec eslint",
                "pnpm lint",
                "pnpm run biome",
                "pnpm run eslint",
                "pnpm run lint",
                "pnpm run-script biome",
                "pnpm run-script eslint",
                "pnpm run-script lint",
                "pnpx biome",
                "pnpx eslint",
                "pnpx lint",
            ],
            "Build",
            84.0),
        R(
            @"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?prettier",
            "rtk prettier",
            [
                "npm exec prettier",
                "npm prettier",
                "npm rum prettier",
                "npm run prettier",
                "npm run-script prettier",
                "npm urn prettier",
                "npm x prettier",
                "npx prettier",
                "pnpm dlx prettier",
                "pnpm exec prettier",
                "pnpm prettier",
                "pnpm run prettier",
                "pnpm run-script prettier",
                "pnpx prettier",
                "prettier",
            ],
            "Build",
            70.0),
        R(
            @"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?next\s+build",
            "rtk next",
            [
                "next build",
                "npm exec next build",
                "npm next build",
                "npm rum next build",
                "npm run next build",
                "npm run-script next build",
                "npm urn next build",
                "npm x next build",
                "npx next build",
                "pnpm dlx next build",
                "pnpm exec next build",
                "pnpm next build",
                "pnpm run next build",
                "pnpm run-script next build",
                "pnpx next build",
            ],
            "Build",
            87.0),
        R(
            @"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?jest(\s+run)?(\s|$)",
            "rtk jest",
            [
                "jest run",
                "jest",
                "npm exec jest run",
                "npm exec jest",
                "npm jest run",
                "npm jest",
                "npm rum jest run",
                "npm rum jest",
                "npm run jest run",
                "npm run jest",
                "npm run-script jest run",
                "npm run-script jest",
                "npm urn jest run",
                "npm urn jest",
                "npm x jest run",
                "npm x jest",
                "npx jest run",
                "npx jest",
                "pnpm dlx jest run",
                "pnpm dlx jest",
                "pnpm exec jest run",
                "pnpm exec jest",
                "pnpm jest run",
                "pnpm jest",
                "pnpm run jest run",
                "pnpm run jest",
                "pnpm run-script jest run",
                "pnpm run-script jest",
                "pnpx jest run",
                "pnpx jest",
            ],
            "Tests",
            99.0),
        R(
            @"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?vitest(\s+run)?(\s|$)",
            "rtk vitest",
            [
                "npm exec vitest run",
                "npm exec vitest",
                "npm rum vitest run",
                "npm rum vitest",
                "npm run vitest run",
                "npm run vitest",
                "npm run-script vitest run",
                "npm run-script vitest",
                "npm urn vitest run",
                "npm urn vitest",
                "npm vitest run",
                "npm vitest",
                "npm x vitest run",
                "npm x vitest",
                "npx vitest run",
                "npx vitest",
                "pnpm dlx vitest run",
                "pnpm dlx vitest",
                "pnpm exec vitest run",
                "pnpm exec vitest",
                "pnpm run vitest run",
                "pnpm run vitest",
                "pnpm run-script vitest run",
                "pnpm run-script vitest",
                "pnpm vitest run",
                "pnpm vitest",
                "pnpx vitest run",
                "pnpx vitest",
                "vitest run",
                "vitest",
            ],
            "Tests",
            99.0),
        R(
            @"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?playwright",
            "rtk playwright",
            [
                "npm exec playwright",
                "npm playwright",
                "npm rum playwright",
                "npm run playwright",
                "npm run-script playwright",
                "npm urn playwright",
                "npm x playwright",
                "npx playwright",
                "playwright",
                "pnpm dlx playwright",
                "pnpm exec playwright",
                "pnpm playwright",
                "pnpm run playwright",
                "pnpm run-script playwright",
                "pnpx playwright",
            ],
            "Tests",
            94.0),
        R(
            @"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?prisma",
            "rtk prisma",
            [
                "npm exec prisma",
                "npm prisma",
                "npm rum prisma",
                "npm run prisma",
                "npm run-script prisma",
                "npm urn prisma",
                "npm x prisma",
                "npx prisma",
                "pnpm dlx prisma",
                "pnpm exec prisma",
                "pnpm prisma",
                "pnpm run prisma",
                "pnpm run-script prisma",
                "pnpx prisma",
                "prisma",
            ],
            "Build",
            88.0),
        R(
            @"^docker\s+(ps|images|logs|run|exec|build|compose\s+(ps|logs|build))",
            "rtk docker",
            ["docker"],
            "Infra",
            85.0),
        R(
            @"^kubectl\s+(get|logs|describe|apply)",
            "rtk kubectl",
            ["kubectl"],
            "Infra",
            85.0),
        R(
            @"^oc\s+(get|logs|describe|apply|status|adm)",
            "rtk oc",
            ["oc"],
            "Infra",
            85.0),
        R(
            @"^tree(\s|$)",
            "rtk tree",
            ["tree"],
            "Files",
            70.0),
        R(
            @"^diff\s+",
            "rtk diff",
            ["diff"],
            "Files",
            60.0),
        R(
            @"^curl\s+",
            "rtk curl",
            ["curl"],
            "Network",
            70.0),
        R(
            @"^wget\s+",
            "rtk wget",
            ["wget"],
            "Network",
            65.0),
        R(
            @"^(python3?\s+-m\s+)?mypy(\s|$)",
            "rtk mypy",
            ["python3 -m mypy", "python -m mypy", "mypy"],
            "Build",
            80.0),
        R(
            @"^ruff\s+(check|format)",
            "rtk ruff",
            ["ruff"],
            "Python",
            80.0),
        R(
            @"^(python[0-9.]*\s+-m\s+)?pytest(\s|$)",
            "rtk pytest",
            ["python3 -m pytest", "python -m pytest", "pytest"],
            "Python",
            90.0),
        R(
            @"^(pip3?|uv\s+pip)\s+(list|outdated|install|show)",
            "rtk pip",
            ["pip3", "pip", "uv pip"],
            "Python",
            75.0),
        R(
            @"^go\s+(test|build|vet)",
            "rtk go",
            ["go"],
            "Go",
            85.0),
        R(
            @"^(?:golangci-lint|golangci)\s+(run)(?:\s|$)",
            "rtk golangci-lint run",
            ["golangci-lint run", "golangci run"],
            "Go",
            85.0),
        R(
            @"^bundle\s+(install|update)\b",
            "rtk bundle",
            ["bundle"],
            "Ruby",
            70.0),
        R(
            @"^(?:bundle\s+exec\s+)?(?:bin/)?(?:rake|rails)\s+test",
            "rtk rake",
            ["bundle exec rails", "bundle exec rake", "bin/rails", "rails", "rake"],
            "Ruby",
            85.0),
        R(
            @"^(?:bundle\s+exec\s+)?rspec(?:\s|$)",
            "rtk rspec",
            ["bundle exec rspec", "bin/rspec", "rspec"],
            "Tests",
            65.0),
        R(
            @"^(?:bundle\s+exec\s+)?rubocop(?:\s|$)",
            "rtk rubocop",
            ["bundle exec rubocop", "rubocop"],
            "Build",
            65.0),
        R(
            @"^aws\s+",
            "rtk aws",
            ["aws"],
            "Infra",
            80.0),
        R(
            @"^psql(\s|$)",
            "rtk psql",
            ["psql"],
            "Infra",
            75.0),
        R(
            @"^ansible-playbook\b",
            "rtk ansible-playbook",
            ["ansible-playbook"],
            "Infra",
            70.0),
        R(
            @"^brew\s+(install|upgrade)\b",
            "rtk brew",
            ["brew"],
            "PackageManager",
            65.0),
        R(
            @"^composer\s+(install|update|require)\b",
            "rtk composer",
            ["composer"],
            "PackageManager",
            65.0),
        R(
            @"^df(\s|$)",
            "rtk df",
            ["df"],
            "System",
            60.0),
        R(
            @"^dotnet\s+build\b",
            "rtk dotnet",
            ["dotnet"],
            "Build",
            70.0),
        R(
            @"^du\b",
            "rtk du",
            ["du"],
            "System",
            60.0),
        R(
            @"^fail2ban-client\b",
            "rtk fail2ban-client",
            ["fail2ban-client"],
            "Infra",
            60.0),
        R(
            @"^gcloud\b",
            "rtk gcloud",
            ["gcloud"],
            "Infra",
            65.0),
        R(
            @"^(?:\./gradlew|gradlew\.bat|gradlew|gradle)(?:\s+(test|build|clean|assemble\w*|install\w*|check|lint\w*|dependencies))?(\s|$)",
            "rtk gradlew",
            ["./gradlew", "gradlew.bat", "gradlew", "gradle"],
            "Build",
            75.0),
        R(
            @"^hadolint\b",
            "rtk hadolint",
            ["hadolint"],
            "Build",
            65.0),
        R(
            @"^helm\b",
            "rtk helm",
            ["helm"],
            "Infra",
            65.0),
        R(
            @"^iptables\b",
            "rtk iptables",
            ["iptables"],
            "Infra",
            60.0),
        R(
            @"^make\b",
            "rtk make",
            ["make"],
            "Build",
            65.0),
        R(
            @"^markdownlint\b",
            "rtk markdownlint",
            ["markdownlint"],
            "Build",
            65.0),
        R(
            @"^mix\s+(compile|format)(\s|$)",
            "rtk mix",
            ["mix"],
            "Build",
            65.0),
        R(
            @"^(?:\./mvnw|mvnw\.cmd|mvnw|mvn)\b(?:\s+\S+)*?\s+(compile|test|integration-test|package|install|verify|deploy)\b",
            "rtk mvn",
            ["./mvnw", "mvnw.cmd", "mvnw", "mvn"],
            "Build",
            82.0),
        R(
            @"^ping\b",
            "rtk ping",
            ["ping"],
            "Network",
            60.0),
        R(
            @"^pio\s+run",
            "rtk pio",
            ["pio"],
            "Build",
            65.0),
        R(
            @"^poetry\s+(install|lock|update)\b",
            "rtk poetry",
            ["poetry"],
            "Python",
            65.0),
        R(
            @"^pre-commit\b",
            "rtk pre-commit",
            ["pre-commit"],
            "Build",
            65.0),
        R(
            @"^ps(\s|$)",
            "rtk ps",
            ["ps"],
            "System",
            60.0),
        R(
            @"^pulumi\s+(preview|up|destroy|refresh|stack)(\s|$)",
            "rtk pulumi",
            ["pulumi"],
            "Infra",
            45.0),
        R(
            @"^quarto\s+render",
            "rtk quarto",
            ["quarto"],
            "Build",
            65.0),
        R(
            @"^rsync\b",
            "rtk rsync",
            ["rsync"],
            "Network",
            65.0),
        R(
            @"^shellcheck\b",
            "rtk shellcheck",
            ["shellcheck"],
            "Build",
            65.0),
        R(
            @"^shopify\s+theme\s+(push|pull)",
            "rtk shopify",
            ["shopify"],
            "Build",
            65.0),
        R(
            @"^sops\b",
            "rtk sops",
            ["sops"],
            "Infra",
            60.0),
        R(
            @"^swift\s+(build|test)\b",
            "rtk swift",
            ["swift"],
            "Build",
            65.0),
        R(
            @"^systemctl\s+status\b",
            "rtk systemctl",
            ["systemctl"],
            "System",
            65.0),
        R(
            @"^terraform\s+plan",
            "rtk terraform",
            ["terraform"],
            "Infra",
            70.0),
        R(
            @"^tofu\s+(fmt|init|plan|validate)(\s|$)",
            "rtk tofu",
            ["tofu"],
            "Infra",
            70.0),
        R(
            @"^trunk\s+build",
            "rtk trunk",
            ["trunk"],
            "Build",
            65.0),
        R(
            @"^uv\s+(sync|pip\s+install)\b",
            "rtk uv",
            ["uv"],
            "Python",
            65.0),
        R(
            @"^yamllint\b",
            "rtk yamllint",
            ["yamllint"],
            "Build",
            65.0),
        R(
            @"^wc(\s|$)",
            "rtk wc",
            ["wc"],
            "Files",
            60.0),
        R(
            @"^gt\s+",
            "rtk gt",
            ["gt"],
            "Git",
            70.0),
        R(
            @"^liquibase(?:\s|$)",
            "rtk liquibase",
            ["liquibase"],
            "Infra",
            65.0),
    ];
}
